caption = "Bird Game"
screen_width = 400
screen_height = 600
background_image_filename = "images/background_image.png"
frame_rate = 30
message_duration = 10
ground_level = 450
pipe_gap = 0.35
bird_speed = 2
